### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by alg** [phoenixframework/phoenix#3957]
### Environment

* Elixir version (elixir -v): 1.10.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.4
* NodeJS version (node -v): v10.20.1
* NPM version (npm -v): 6.14.4
* Operating system: Ubuntu 18.04.3 LTS

### Expected behavior

No undefined is not a function error.

### Actual behavior

Getting `Uncaught TypeError: undefined is not a function` in `Socket.leaveOpenTopic()` at `this.channels.find(...)`. Error points to `find` that isn't defined for some reason. The error happened on multiple occasions as reported by Rollbar.JS and it's exclusive to Win 7/10 + Chrome 83. However, not all such users are affected. We are still to figure under what conditions exactly does it happen.

From unobfuscated call stack I could trace it back to:

- LiveSocket.connect()
- LiveSocket.joinRootViews()
- DOM.all()
- Array.forEach()
- LiveSocket.joinRootView()
- View.join()
- LiveSocket.wrapPush()
- Channel.join()
- Channel.rejoin()
- [Socket.leaveOpenTopic()](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L1145) at this.channels.find()

For the past 5 days we hit it 12 times for 4 different users when they open pages with Live View. **It started happening after upgrading Phoenix to 1.5.4 from 1.4.17**. We also upgraded Phoenix Live View to 0.14.4 from 0.14.0, but since the error resides on the Socket side, I assume Phoenix project is the right one to file the issue.

**Comment by ivanovv** [comment]
this is the same as #3965 and the fix for us was changing this

```js
              {
                key: "leaveOpenTopic",
                value: function (e) {
                  var t = this.channels.find(function (t) {
                    return t.topic === e && (t.isJoined() || t.isJoining());
                  });
```

to this

```js
              {
                key: "leaveOpenTopic",
                value: function (e) {
                  var t = this.channels.filter(function (t) {
                    return t.topic === e && (t.isJoined() || t.isJoining());
                  })[0];
```

The only thing that I don't understand is why Chrome is affected. According to https://caniuse.com/?search=Array.prototype.find `find` is supported since v45. Are you sure that it is Chrome, not some other browser?

**Comment by alg** [comment]
@ivanovv pretty sure it was Chrome. That is what puzzled us in the first place.

**Comment by chrismccord** [comment]
If you have more information on this not being defined outside of IE11, please let us know. For those that require IE11 support, the necessary array polyfill and/or babel build w/ proper presets will work for older browsers. Thanks!
