### ISSUE TITLE
CodeReloader error in phx.new app with Elixir 1.18

### ISSUE THREAD

**Issue by leifmetcalf** [phoenixframework/phoenix#6040]
### Environment

* Elixir version (elixir -v): 1.18.1
* Phoenix version (mix deps): 1.7.18
* Operating system: Ubuntu 24.04.1

### Bug
One of my apps started giving `** (ArgumentError) The module Phoenix.CodeReloader was given as a child to a supervisor
but it does not implement child_spec/1.` when I upgraded from Elixir 1.17.3 to 1.18.1.

### Reproduction
```bash
git clone https://github.com/phoenixframework/phoenix.git
# last commit as of 2025-01-08
git checkout 06e3525edf9bb5918785ce929433761c11935d70
cd phoenix/installer
mix phx.new my_app
cd my_app
# replace phoenix version with 1.7.18
perl -i -pe 's/github: "phoenixframework\/phoenix", override: true/"~> 1.7.18"/' mix.exs
mix deps.get
mix assets.build
```

This fails with Elixir 1.18.1, but succeeds with Elixir 1.17.3. If I use the git main version of phoenix then it works.

I'm using the git main version of `phx.new` with an older release of `phoenix` so it's expected something broke. I'm just surprised it works with Elixir 1.17.3.

`mix assets.build` output with Elixir 1.18.1:
```
==> phoenix
Compiling 71 files (.ex)
Generated phoenix app
==> phoenix_live_reload
Compiling 5 files (.ex)
Generated phoenix_live_reload app
==> phoenix_live_view
Compiling 39 files (.ex)
Generated phoenix_live_view app
==> phoenix_live_dashboard
Compiling 36 files (.ex)
Generated phoenix_live_dashboard app
** (ArgumentError) The module Phoenix.CodeReloader was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Phoenix.CodeReloader,
      start: {Phoenix.CodeReloader, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information

    (elixir 1.18.1) lib/supervisor.ex:797: Supervisor.init_child/1
    (elixir 1.18.1) lib/supervisor.ex:905: Supervisor.child_spec/2
    (elixir 1.18.1) lib/enum.ex:1714: Enum."-map/2-lists^map/1-1-"/2
    (mix 1.18.1) lib/mix/pubsub.ex:77: Mix.PubSub.listener_supervisor/0
    (mix 1.18.1) lib/mix/pubsub.ex:59: Mix.PubSub.start_listeners/0
    (mix 1.18.1) lib/mix/tasks/deps.loadpaths.ex:74: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.18.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.1) lib/mix/task.ex:545: Mix.Task.get_task_or_run/3
```

**Comment by josevalim** [comment]
Please delete the `listeners: [...]` configuration from your mix.exs. Keep in mind that an app generated with Phoenix main downgraded to v1.7 may use configurations and settings that are not available in v1.7, which seems to be the case here.

**Comment by leifmetcalf** [comment]
Ah, so Elixir versions before 1.18 ignore the `listeners: [...]` field and that's why it seemed like upgrading Elixir broke something. Thanks Jose!
