### ISSUE TITLE
Phoenix.ChannelTest requires :ex_unit and thus breaks espec

### ISSUE THREAD

**Issue by Kukunin** [phoenixframework/phoenix#3223]
Since 1.4.0 version, `Phoenix.ChannelTest.refute_broadcast` and similar functions fetches `:ex_unit` application configuration: https://hexdocs.pm/phoenix/Phoenix.ChannelTest.html#assert_broadcast/3

That's ok if you use `ex_unit`, but that's not a single test runner in the elixir ecosystem. I use ESpec, and I don't have `ex_unit` application running, so it crashes for me. Also, it's problematic to start `ex_unit` because espec starts some parts of it already, expecting nobody will use two test runners at the same time.

Reported issue to espec: https://github.com/antonmi/espec_phoenix/issues/54

### Environment

* Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.0
* NodeJS version (node -v): v10.7.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS High Sierra

### Expected behavior

`Phoenix.ChannelTest` runs well with other test runners beside `ex_unit`. It can fall back to default hard-coded value (100ms)

### Actual behavior

It crashes with

```
** (ArgumentError) could not fetch application environment :refute_receive_timeout for application :ex_unit because the application was not loaded/started. If your application depends on :ex_unit at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
```

**Comment by chrismccord** [comment]
Our testing tools only support ExUnit. Thanks!

**Comment by Apelsinka223** [comment]
Hi, I have same issue and I use ExUnit. I define helper function in test case, it worked with phoenix 1.3.4, but in new project I use 1.4.3 and it raises error.
```
defmodule ChatWeb.SubscriptionCase do
   use ExUnit.CaseTemplate
    ...
   using do
     quote do
       ...
       import unquote(__MODULE__)
     end
   end
  ...

  # the function
  def subscribe_on_query(socket, query) do
    ref = push_doc(socket, query)
    assert_reply(ref, :ok, %{subscriptionId: subscription_id})

    subscription_id
  end
end
```
and got error
```
== Compilation error in file test/support/subscription_case.ex ==
** (ArgumentError) could not fetch application environment :assert_receive_timeout for application :ex_unit because the application was not loaded/started. If your application depends on :ex_unit at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
    (elixir) lib/application.ex:495: Application.fetch_env!/2
    (phoenix) expanding macro: Phoenix.ChannelTest.assert_reply/3
    test/support/subscription_case.ex:55: ChatWeb.SubscriptionCase.subscribe_on_query/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

Already tried to add :ex_unit in : extra_applications and in test_helper.exs added check, but it still doesn't work.
```
ExUnit.configure formatters: [JUnitFormatter, ExUnit.CLIFormatter]
ExUnit.start()
{:ok, _} = Application.ensure_all_started(:ex_unit) # - this

Ecto.Adapters.SQL.Sandbox.mode(Chat.Repo, :manual)
```

**Comment by kbredemeier** [comment]
Just found this via google. I ran into a similar problem as @Apelsinka223 after I updated a project to elixir 1.9.4. All case templates that are using `assert_receive` or `refute_receive` stopped compiling. I fixed this by adding `Application.ensure_all_started(:ex_unit)` to the top of the failing case templates.
