### ISSUE TITLE
Endpoint breaks when upgrading from Phoenix 16 to 17.0

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix#1142]
Just opened this same issue in phoenix/guides, since it seems the guide will also need updating.

Just tried upgrading from version 16 to 17, following the guide at http://www.phoenixframework.org/v0.10.0/blog. When I try to run the app the following error is thrown:

== Compilation error on file lib/myapp/endpoint.ex ==
** (CompileError) lib/myapp/endpoint.ex:1: function router/2 undefined
(stdlib) lists.erl:1337: :lists.foreach/2
(stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

The app is using the standard boilerplate endpoint.ex file:

defmodule Myapp.Endpoint do
use Phoenix.Endpoint, otp_app: :myapp

# Serve at "/" the static files from "priv/static" directory.
#
# You should set gzip to true if you are running phoenix.digest
# when deploying your static files in production.
plug Plug.Static,
at: "/", from: :myapp, gzip: false,
only: ~w(css images js favicon.ico robots.txt)

# Code reloading can be explicitly enabled under the
# :code_reloader configuration of your endpoint.
if code_reloading? do
plug Phoenix.LiveReloader
plug Phoenix.CodeReloader
end

plug Plug.Logger

plug Plug.Parsers,
parsers: [:urlencoded, :multipart, :json],
pass: ["/"],
json_decoder: Poison

plug Plug.MethodOverride
plug Plug.Head

plug Plug.Session,
store: :cookie,
key: "_myapp_key",
signing_salt: "4R5ILud2"

plug :router, Myapp.Router
end

Thanks for your help!

**Comment by chrismccord** [comment]
`plug :router` was deprecated in the last release, change `plug :router, Myapp.Router` to `plug Myapp.Router` and you should be all set.

**Comment by Alamoz** [comment]
Thanks again! Would someone ever want to plug in a router anywhere other than in lib/myapp/endpoint.ex?

**Comment by chrismccord** [comment]
Yes, you could forward to another router or have another plug call a router directly, since it's just a plug itself.
